Fix artifact poisoning in sonar workflow

diff --git a/.github/workflows/sonar.yaml b/.github/workflows/sonar.yaml
--- a/.github/workflows/sonar.yaml
+++ b/.github/workflows/sonar.yaml
@@ -63,7 +63,16 @@ jobs:
           name: compiled-classes
           github-token: ${{ secrets.GITHUB_TOKEN }}
           run-id: ${{ github.event.workflow_run.id }}
-          path: target/classes
+          path: ${{ runner.temp }}/artifacts/compiled-classes
+      # Verify and move compiled classes
+      - name: Verify and Move Compiled Classes
+        run: |
+          if [ -d "${{ runner.temp }}/artifacts/compiled-classes" ]; then
+            mv ${{ runner.temp }}/artifacts/compiled-classes/* target/classes/
+          else
+            echo "Compiled classes not found!"
+            exit 1
+          fi
       # Download Jacoco XML coverage files
       - name: Download Coverage Reports
         uses: actions/download-artifact@v4
@@ -71,7 +80,16 @@ jobs:
           name: coverage-reports
           github-token: ${{ secrets.GITHUB_TOKEN }}
           run-id: ${{ github.event.workflow_run.id }}
-          path: target/site/jacoco
+          path: ${{ runner.temp }}/artifacts/coverage-reports
+      # Verify and move coverage reports
+      - name: Verify and Move Coverage Reports
+        run: |
+          if [ -d "${{ runner.temp }}/artifacts/coverage-reports" ]; then
+            mv ${{ runner.temp }}/artifacts/coverage-reports/* target/site/jacoco/
+          else
+            echo "Coverage reports not found!"
+            exit 1
+          fi
       # SonarCloud Scan analysis and push
       - name: SonarCloud Scan
         env:
